
name: My-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  my_demo_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
   

      # Runs a single command using the runners shell
    #  - name: Run a one-line script
   #   - name: Install allure
   #     run: apt-add-repository ppa:qameta/allure
        
      - name: Update allure
        run: apt-get update
        
      - name: Install allure  
        run: apt-get install allure
        
      - name: Generate report  
        run: mvn allure:serve
        
      - name: Run a one-line script  
        run: mvn clean test
        
        
 #     - name: Run allure
 #       run: mvn allure:serve
 #     - name: Generate allure report 
  #      run: mvn allure:report
