
name: My-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  my_demo_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
   

      # Runs a single command using the runners shell
    #  - name: Run a one-line script
   #   - name: Install allure
   #     run: apt-add-repository ppa:qameta/allure
     
      - name: Run a one-line script  
      - run: mvn test
      - run: mvn allure:serve
     
   #     
        
 #     - name: Run allure
 #       run: mvn allure:serve
 #     - name: Generate allure report 
  #      run: mvn allure:report
