
name: My-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  my_demo_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
    name: 'Allure report'
    description: 'Generate Allure report for test suite'
    inputs:
      results-dir:  # id of input
        description: 'Allure test result data dir'
        required: true
        default: 'allure-results'
      report-dir:
        description: 'Allure report target dir'
        required: true
        default: 'allure-report'

   

      # Runs a single command using the runners shell
    #  - name: Run a one-line script
   #   - name: Install allure
   #     run: apt-add-repository ppa:qameta/allure
      runs:
       using: 'docker'
       image: 'Dockerfile'
      args:
      - ${{ inputs.results-dir }}
      - ${{ inputs.report-dir }}
      - name: Run a one-line script  
        run: mvn test
     
  
        
 #     - name: Run allure
 #       run: mvn allure:serve
 #     - name: Generate allure report 
  #      run: mvn allure:report
