name: Super-Linter

on: push


jobs:

  super-lint:
 
    name: Lint code base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Run Super-Linter
        run: mvn clean test
      
      - name: Allure report
        uses: afiore/action-allure-report@v0.1.0
      
      - name: Run docker
        run: docker build . -t allure-gen
        
      - name: Run docker  
        run: docker run -v ${PWD}:/github/workspace allure-gen allure-results allure-report
      
      
        
        
        
        
        

